# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 52c35829a65b9644ce3fe881841ba55f8c318d69ad5d8c9fd4a4d84f45eda39db717b9fb0a489687c4226cab05758ff5ff56ae9c353676c844db31d75ba53061

test:
  secret_key_base: 292beadbdc3dccf2b6321ddf8cb6c1bdc5027107d5b94d3ca2e3f9fac3b4fc1e68c3034d1f181e4b0aab823c4a97b1802a1aed497190a539afad0c6dd9872cbf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
